# Generated by Django 5.0 on 2023-12-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='posts',
            new_name='post',
        ),
    ]
