# Generated by Django 5.0 on 2023-12-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_posts_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
    ]
