# Generated by Django 5.0 on 2023-12-30 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_comments_comments_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followiings',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
